name: UI Change Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign-ui-reviewer:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, '- [x] UI changes') || contains(github.event.pull_request.body, '- [X] UI changes')
    steps:
      - name: Assign UI Reviewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          UI_REVIEWER: "rtwell"
        run: |
          gh pr edit $PR_URL --add-reviewer $UI_REVIEWER
